/* Stitch design tokens — shared across Facebook flow */
if (typeof tailwind !== "undefined") {
  tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-tertiary-container": "#b9f6f1",
          "on-primary-container": "#a3faef",
          "surface-container-low": "#eff4ff",
          "inverse-primary": "#80d5cb",
          "inverse-surface": "#213145",
          "surface-container-high": "#dce9ff",
          error: "#ba1a1a",
          "error-container": "#ffdad6",
          "tertiary-fixed": "#b1eee9",
          background: "#f8f9ff",
          "on-background": "#0b1c30",
          "surface-container-lowest": "#ffffff",
          "on-secondary": "#ffffff",
          "tertiary-fixed-dim": "#95d1cd",
          "on-secondary-fixed-variant": "#7f2b00",
          "primary-container": "#0f766e",
          "surface-variant": "#d3e4fe",
          "on-surface": "#0b1c30",
          outline: "#6e7977",
          "primary-fixed": "#9cf2e8",
          "on-error-container": "#93000a",
          "tertiary-container": "#37736f",
          surface: "#f8f9ff",
          "on-primary-fixed-variant": "#00504a",
          "on-tertiary-fixed": "#00201e",
          "on-tertiary": "#ffffff",
          "on-error": "#ffffff",
          "on-secondary-container": "#571a00",
          secondary: "#a73a00",
          "secondary-fixed": "#ffdbce",
          "surface-bright": "#f8f9ff",
          "secondary-fixed-dim": "#ffb599",
          "surface-container-highest": "#d3e4fe",
          "secondary-container": "#fd651e",
          "on-surface-variant": "#3e4947",
          "surface-container": "#e5eeff",
          tertiary: "#1a5a57",
          "surface-tint": "#006a63",
          "surface-dim": "#cbdbf5",
          "primary-fixed-dim": "#80d5cb",
          "inverse-on-surface": "#eaf1ff",
          "on-tertiary-fixed-variant": "#094f4c",
          primary: "#005c55",
          "outline-variant": "#bdc9c6",
          "on-secondary-fixed": "#370e00",
          "on-primary-fixed": "#00201d",
          "on-primary": "#ffffff",
        },
        borderRadius: {
          DEFAULT: "0.25rem",
          lg: "0.5rem",
          xl: "0.75rem",
          full: "9999px",
        },
        spacing: {
          gutter: "20px",
          md: "16px",
          margin: "24px",
          xl: "32px",
          "2xl": "48px",
          sm: "8px",
          base: "4px",
          lg: "24px",
          xs: "4px",
        },
        fontFamily: {
          sans: ["Inter", "system-ui", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "display-lg": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
        },
        fontSize: {
          "body-md": ["14px", { lineHeight: "20px" }],
          "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
          "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
          "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
          "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
          "body-sm": ["13px", { lineHeight: "18px" }],
          "body-lg": ["16px", { lineHeight: "24px" }],
        },
      },
    },
  };
}
